import { Link } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import './AboutPage.css'

export default function AboutPage() {
  const { t } = useTranslation()
  return (
    <div className="about-page">
      <nav className="about-nav">
        <Link to="/" className="about-logo">Wenap</Link>
        <div style={{ display: 'flex', gap: 16 }}>
          <Link to="/pricing" className="about-nav-link">Pricing</Link>
          <Link to="/login" className="about-nav-link">Sign in</Link>
        </div>
      </nav>

      <div className="about-content">
        <h1>How Wenap Works</h1>
        <p className="about-lead">Wenap is an AI-powered investment research assistant. It does not give financial advice. Here's exactly how it works.</p>

        <section className="about-section">
          <h2>1. Data Sources</h2>
          <p>For each analysis, Wenap gathers data from multiple sources:</p>
          <ul>
            <li><strong>Alpha Vantage</strong> — real-time price, volume, fundamental overview (P/E, market cap, etc.)</li>
            <li><strong>OpenRouter AI search</strong> — recent news, SEC filings, analyst reports, macro context</li>
            <li><strong>Historical predictions</strong> — our own database of past predictions for accuracy tracking</li>
          </ul>
        </section>

        <section className="about-section">
          <h2>2. AI Model Tiers</h2>
          <p>The quality of analysis depends on your subscription tier:</p>
          <table className="about-table">
            <thead>
              <tr><th>Tier</th><th>Model</th><th>Sources</th><th>Features</th></tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>Free</strong></td>
                <td>Gemini 2.5 Flash Lite</td>
                <td>5</td>
                <td>Six-dimension scoring, scenarios</td>
              </tr>
              <tr>
                <td><strong>Pro</strong></td>
                <td>Gemini 2.5 Flash Lite</td>
                <td>8</td>
                <td>+ Unlimited runs, action line, key events, insider summary, peer comparison</td>
              </tr>
              <tr>
                <td><strong>Pro+</strong></td>
                <td>GPT-5.4 Mini</td>
                <td>8</td>
                <td>+ Bull/Bear debate, Critic's corner, PDF export, Compare</td>
              </tr>
            </tbody>
          </table>
        </section>

        <section className="about-section">
          <h2>3. Six-Dimension Scoring</h2>
          <p>Every analysis scores the asset on six dimensions (0–100):</p>
          <ol>
            <li><strong>Fundamental Health</strong> — earnings quality, balance sheet, cash flow</li>
            <li><strong>Technical Trend</strong> — price momentum, moving averages, volume patterns</li>
            <li><strong>Market Sentiment</strong> — analyst consensus, options flow, short interest</li>
            <li><strong>Industry / Sector Dynamics</strong> — competitive position, sector tailwinds/headwinds</li>
            <li><strong>Macro / Policy Risk</strong> — interest rate sensitivity, geopolitical exposure, regulatory risk</li>
            <li><strong>Supply Chain Risk</strong> — concentration risk, key supplier dependencies</li>
          </ol>
          <p>The overall score is a weighted average of the six dimensions. Weights are determined by the AI based on asset type.</p>
        </section>

        <section className="about-section">
          <h2>4. Signal Generation</h2>
          <p>The signal (STRONG BUY / BUY / HOLD / SELL / STRONG SELL) is generated by the AI model based on the composite score, risk/reward ratio, and horizon-adjusted scenarios. It is <em>not</em> a guaranteed prediction.</p>
        </section>

        <section className="about-section">
          <h2>5. Accuracy Tracking</h2>
          <p>Every prediction is stored with a target horizon (1m / 3m / 6m / 1y / 2y). After the horizon expires, Wenap automatically fetches the actual price change and marks the prediction as:</p>
          <ul>
            <li><strong>Correct</strong> — signal direction matched actual return</li>
            <li><strong>Incorrect</strong> — signal direction did not match</li>
            <li><strong>Neutral</strong> — HOLD signal (counted separately)</li>
          </ul>
          <p>Accuracy statistics are publicly visible at <Link to="/accuracy">/accuracy</Link>.</p>
        </section>

        <section className="about-section">
          <h2>6. Disclaimer</h2>
          <p className="about-disclaimer">Wenap is not a registered investment advisor. All content is for informational and educational purposes only. Past prediction accuracy does not guarantee future results. Never invest based solely on AI-generated analysis. Always do your own research and consult a qualified financial professional before making investment decisions.</p>
          <p className="about-disclaimer">
            <Link to="/disclaimer">{t('legal.nav.disclaimer')}</Link>
            {' · '}
            <Link to="/terms">{t('legal.nav.terms')}</Link>
            {' · '}
            <Link to="/privacy">{t('legal.nav.privacy')}</Link>
          </p>
        </section>
      </div>

      <footer className="about-footer">
        <Link to="/">Home</Link>
        <Link to="/pricing">Pricing</Link>
        <Link to="/accuracy">Accuracy</Link>
        <Link to="/disclaimer">{t('legal.nav.disclaimer')}</Link>
        <Link to="/privacy">{t('legal.nav.privacy')}</Link>
        <Link to="/terms">{t('legal.nav.terms')}</Link>
        <Link to="/app">App</Link>
      </footer>
    </div>
  )
}
